#!/bin/sh

killall sxhkd
sxhkd &

killall picom
picom &

killall polybar
polybar main &

killall dyn-wall-rs
dyn-wall-rs -a $HOME/pictures/dynamic-wallpapers/lakeside &

bspc monitor primary -d h b w wr p pr v1 v2 c m

if [ $(bspc query -M | wc -w) -eq 2 ]; then
  bspc desktop b  -m DP-1-3
  bspc desktop wr -m DP-1-3
  bspc desktop pr -m DP-1-3
  bspc desktop v2 -m DP-1-3
  bspc desktop m  -m DP-1-3

  bspc desktop Desktop -r
  bspc desktop Desktop -r
  bspc desktop Desktop -r
  bspc desktop Desktop -r
  bspc desktop Desktop -r

  bspc wm -O eDP-1 DP-1-3
fi

# bspc config ignore_ewmh_focus true
# bspc config ignore_ewmh_fullscreen true
# bspc config ignore_ewmh_struts true

bspc config active_border_color "#73d0ff"
bspc config focused_border_color "#ffcc66"

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config pointer_modifier mod4
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

bspc config border_width 2
bspc config window_gap   12
bspc config top_padding  24

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -r "*"

bspc rule -a kakoune-connect state=floating center=true rectangle=1200x800+0+0
bspc rule -a floating-center state=floating center=true rectangle=800x800+0+0
bspc rule -a floating-right state=floating rectangle=800x800+1000+200
bspc rule -a floating-left state=floating rectangle=800x800+120+200
bspc rule -a Zeal:zeal state=floating center=true rectangle=1200x800+0+0

bspc rule -a Dialog manage=off
bspc rule -a Splash manage=off
bspc rule -a Utility manage=off
